export const BgColor = {
  primary: 'bg-blue-500',
  warning: 'bg-orange-500',
  danger: 'bg-red-600',
  success: 'bg-green-500',
  secondary: 'bg-gray-200',
  light: 'bg-slate-100',
};

export const BorderColor = {
  warning: 'border-amber-400',
  danger: 'border-red-400',
  secondary: 'border-zinc-300',
  primary: 'border-sky-300',
  default: 'border-gray-200',
};

export const TextColor = {
  default: 'text-dark',
  secondary: 'text-zinc-500',
  danger: 'text-red-500',
  primary: 'bg-blue-600',
  warning: 'text-amber-500',
};

export const Symbol = {
  longDash: '—',
  copyright: '©',
};

export const SvgIcon = {
  login: '/assets/flaticon/regular/fi-rr-sign-in-alt.svg',
  logout: '/assets/flaticon/regular/fi-rr-sign-out-alt.svg',
  trash: '/assets/flaticon/regular/fi-rr-trash.svg',
  search: '/assets/flaticon/regular/fi-rr-search.svg',
  cross: '/assets/flaticon/regular/fi-rr-cross.svg',
  'cross-circle': '/assets/flaticon/regular/fi-rr-cross-circle.svg',
  info: '/assets/flaticon/regular/fi-rr-info.svg',
  exclamation: '/assets/flaticon/regular/fi-rr-exclamation.svg',
  help: '/assets/flaticon/regular/fi-rr-interrogation.svg',
  'shield-exclamation': '/assets/flaticon/regular/fi-rr-shield-exclamation.svg',
  user: '/assets/flaticon/regular/fi-rr-user.svg',
  resources: '/assets/flaticon/regular/fi-rr-resources.svg',
  shop: '/assets/flaticon/regular/fi-rr-shop.svg',
  'box-alt': '/assets/flaticon/regular/fi-rr-box-alt.svg',
  settings: '/assets/flaticon/regular/fi-rr-settings.svg',
  building: '/assets/flaticon/regular/fi-rr-building.svg',
  home: '/assets/flaticon/regular/fi-rr-home.svg',
  'man-head': '/assets/flaticon/regular/fi-rr-man-head.svg',
  'woman-head': '/assets/flaticon/regular/fi-rr-woman-head.svg',
  package: '/assets/flaticon/regular/fi-rr-package.svg',
  mountains: '/assets/flaticon/regular/fi-rr-mountains.svg',
  'arrow-left': '/assets/flaticon/regular/fi-rr-arrow-left.svg',
  'arrow-right': '/assets/flaticon/regular/fi-rr-arrow-right.svg',
  'angle-right': '/assets/flaticon/regular/fi-rr-angle-right.svg',
  'angle-left': '/assets/flaticon/regular/fi-rr-angle-left.svg',
  'angle-down': '/assets/flaticon/regular/fi-rr-angle-down.svg',
  'angle-up': '/assets/flaticon/regular/fi-rr-angle-up.svg',
  add: '/assets/flaticon/regular/fi-rr-add.svg',
  'layout-fluid': '/assets/flaticon/regular/fi-rr-layout-fluid.svg',
  stop: '/assets/flaticon/regular/fi-rr-stop.svg',
  marker: '/assets/flaticon/regular/fi-rr-marker.svg',
  'home-location-alt': '/assets/flaticon/regular/fi-rr-home-location-alt.svg',
  'location-alt': '/assets/flaticon/regular/fi-rr-location-alt.svg',
  'shopping-bag': '/assets/flaticon/regular/fi-rr-shopping-bag.svg',
  briefcase: '/assets/flaticon/regular/fi-rr-briefcase.svg',
  check: '/assets/flaticon/regular/fi-rr-check.svg',
  clock: '/assets/flaticon/regular/fi-rr-clock.svg',
  protractor: '/assets/flaticon/regular/fi-rr-protractor.svg',
  'minus-small': '/assets/flaticon/regular/fi-rr-minus-small.svg',
  'plus-small': '/assets/flaticon/regular/fi-rr-plus-small.svg',
  'truck-couch': '/assets/flaticon/regular/fi-rr-truck-couch.svg',
  'truck-loading': '/assets/flaticon/regular/fi-rr-truck-loading.svg',
  form: '/assets/flaticon/regular/fi-rr-form.svg',
  pencil: '/assets/flaticon/regular/fi-rr-pencil.svg',
  database: '/assets/flaticon/regular/fi-rr-database.svg',
  receipt: '/assets/flaticon/regular/fi-rr-receipt.svg',
  'arrow-square-left': '/assets/flaticon/regular/fi-rr-arrow-square-left.svg',
  'arrow-square-right': '/assets/flaticon/regular/fi-rr-arrow-square-right.svg',
  'arrow-small-left': '/assets/flaticon/regular/fi-rr-arrow-small-left.svg',
  'arrow-small-right': '/assets/flaticon/regular/fi-rr-arrow-small-right.svg',
  'head-side-thinking': '/assets/flaticon/regular/fi-rr-head-side-thinking.svg',
  garage: '/assets/flaticon/regular/fi-rr-garage.svg',
  'garage-open': '/assets/flaticon/regular/fi-rr-garage-open.svg',
  'paper-plane': '/assets/flaticon/regular/fi-rr-paper-plane.svg',
  arrows: '/assets/flaticon/regular/fi-rr-arrows.svg',
  'chart-histogram': '/assets/flaticon/regular/fi-rr-chart-histogram.svg',
  'shopping-bag-add': '/assets/flaticon/regular/fi-rr-shopping-bag-add.svg',
  bell: '/assets/flaticon/regular/fi-rr-bell.svg',
  camping: '/assets/flaticon/regular/fi-rr-camping.svg',
  'book-alt': '/assets/flaticon/regular/fi-rr-book-alt.svg',
  exchange: '/assets/flaticon/regular/fi-rr-exchange.svg',
  notebook: '/assets/flaticon/regular/fi-rr-notebook.svg',
  'time-past': '/assets/flaticon/regular/fi-rr-time-past.svg',
  download: '/assets/flaticon/regular/fi-rr-download.svg',
  'cloud-download': '/assets/flaticon/regular/fi-rr-cloud-download.svg',
  lock: '/assets/flaticon/regular/fi-rr-lock.svg',
  unlock: '/assets/flaticon/regular/fi-rr-unlock.svg',

  'cube-sr': '/assets/flaticon/solid/fi-sr-cube.svg',
  'cross-circle-sr': '/assets/flaticon/solid/fi-sr-cross-circle.svg',
  'exclamation-sr': '/assets/flaticon/solid/fi-sr-exclamation.svg',
  'info-sr': '/assets/flaticon/solid/fi-sr-info.svg',
  'help-sr': '/assets/flaticon/solid/fi-sr-interrogation.svg',
  'shield-exclamation-sr':
    '/assets/flaticon/solid/fi-sr-shield-exclamation.svg',
  'user-sr': '/assets/flaticon/solid/fi-sr-user.svg',
  'mountains-sr': '/assets/flaticon/solid/fi-sr-mountains.svg',
  'add-sr': '/assets/flaticon/solid/fi-sr-add.svg',
  'camera-sr': '/assets/flaticon/solid/fi-sr-camera.svg',
  'archive-sr': '/assets/flaticon/solid/fi-sr-archive.svg',
  'apps-sr': '/assets/flaticon/solid/fi-sr-apps.svg',
  'calendar-sr': '/assets/flaticon/solid/fi-sr-calendar.svg',
  'head-side-thinking-sr':
    '/assets/flaticon/solid/fi-sr-head-side-thinking.svg',

  'cross-alt': '/assets/svg/cross.svg',
  'qr-code': '/assets/svg/qr-code.svg',

  provider: '/assets/flaticon/regular/ff-rr-service.svg',
  loader: '/assets/flaticon/regular/ff-rr-loading.svg',
  warehouse: '/warehouse.svg',
  notification: '/assets/flaticon/regular/ff-rr-notification.svg',
  'notification-is-read': '/assets/flaticon/regular/ff-rr-dry-clean.svg'
};
