export const PermissionList = {
  LOGIN: { key: 'LOGIN' },

  // Tài khoản
  CREATE_USER: { key: 'CREATE_USER' },
  CREATE_ROLE: { key: 'CREATE_ROLE' },

  // Nghiệp vụ kho cơ bản
  CREATE_PRODUCT: { key: 'CREATE_PRODUCT' },
  CREATE_LOT: { key: 'CREATE_LOT' },
  CREATE_RACK: { key: 'CREATE_RACK' },
  CREATE_UOM: { key: 'CREATE_UOM' },

  // Đối tác
  CREATE_PROVIDER: { key: 'CREATE_PROVIDER' },
  CREATE_CUSTOMER: { key: 'CREATE_CUSTOMER' },

  // Nghiệp vụ nhập kho
  CREATE_BR: { key: 'CREATE_BR' },
  CREATE_PO: { key: 'CREATE_PO' },
  CREATE_IMPORT: { key: 'CREATE_IMPORT' },
  UPDATE_SUBMITTED_BR: { key: 'UPDATE_SUBMITTED_BR' },
  UPDATE_SUBMITTED_PO: { key: 'UPDATE_SUBMITTED_PO' },
  UPDATE_SUBMITTED_IMPORT: { key: 'UPDATE_SUBMITTED_IMPORT' },
  // CREATE_PRODUCT_STOCK: { key: 'CREATE_PRODUCT_STOCK' },

  // Nghiệp vụ xuất kho
  CREATE_SO: { key: 'CREATE_SO' },
  CREATE_EXPORT: { key: 'CREATE_EXPORT' },
  UPDATE_SUBMITTED_SO: { key: 'UPDATE_SUBMITTED_SO' },
  UPDATE_SUBMITTED_EXPORT: { key: 'UPDATE_SUBMITTED_EXPORT' },
  // CREATE_PRODUCT_STOCK_EXPORT: { key: 'CREATE_PRODUCT_STOCK_EXPORT' },

  UPDATE_PRODUCTS_LOCATION: { key: 'UPDATE_PRODUCTS_LOCATION' },
};

// 0: "LOGIN"
// 1: "CREATE_USER"
// 2: "CREATE_PRODUCT"
// 3: "CREATE_PROVIDER"
// 4: "CREATE_CUSTOMER"
// 5: "CREATE_BR"
// 6: "CREATE_PO"
// 7: "CREATE_SO"
// 8: "CREATE_IMPORT"
// 9: "CREATE_EXPORT"
// 10: "CREATE_PRODUCT_STOCK"
// 11: "CREATE_ROLE"
// 12: "CREATE_LOT"
// 13: "CREATE_RACK"
// 14: "UPDATE_SUBMITTED_BR"
// 15: "UPDATE_SUBMITTED_PO"
// 16: "UPDATE_SUBMITTED_SO"
// 17: "UPDATE_SUBMITTED_IMPORT"
// 18: "UPDATE_SUBMITTED_EXPORT"
// 19: "UPDATE_PRODUCTS_LOCATION"
